# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@master
        with:
          node-version: 12

      - name: Check & Build
        run: |
          npm ci
          npm run test
          npm run check-release-version

      - name: Use npm
        uses: actions/setup-node@master
        with:
          node-version: 12
      - name: Publish npm
        run: |
          npm config set //registry.npmjs.org/:_authToken=${{ secrets.npm_token }}
          npm publish -registry https://registry.npmjs.org --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      - name: Use gpr
        uses: actions/setup-node@master
        with:
          node-version: 12
      - name: Publish gpr
        run: |
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}
          npm publish -registry https://npm.pkg.github.com/@mosby-zhou --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Deploy github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
